### ISSUE TITLE
Jerrie_Feng

### ISSUE THREAD

**Issue by jerryjerrie** [bcb420-2022/Student_Wiki#12]
sorry made a mistake in using wrong github the previous issue:
 repository for bcb420 for Jerrie Feng

**Comment by risserlin** [comment]
created repo - Jerrie_Feng in the bcb420-2022 organizations and added you to the Students team. You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
If you have any issues please let me know.
