### ISSUE TITLE
Dae-won (Sean) Gong

### ISSUE THREAD

**Issue by daewon-gong** [bcb420-2022/Student_Wiki#19]
github name: daewon-gong

**Comment by risserlin** [comment]
in quercus the only Gong I have listed is Sean Gong.  Are you the same person?

**Comment by daewon-gong** [comment]
Oh yes, Sean is my nickname sorry for the confusion.

**Comment by risserlin** [comment]
created repo - Sean_Gong in the bcb420-2022 organizations and added you to the Students team. You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
If you have any issues please let me know.

I kept the repository as the listed name in quercus so it is easy to associated the repo with the right person.
