### ISSUE TITLE
Sabbir_Hossain

### ISSUE THREAD

**Issue by itsSabbir** [bcb420-2022/Student_Wiki#25]
GitHub username: itsSabbir
Student name: Sabbir Hossain
GitHub account [link](https://github.com/itsSabbir)

**Comment by risserlin** [comment]
created repo - Sabbir Hossain in the bcb420-2022 organizations and added you to the Students team. You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
If you have any issues please let me know.
