### ISSUE TITLE
Lori-tan

### ISSUE THREAD

**Issue by Lori-tan** [bcb420-2022/Student_Wiki#27]

**Comment by risserlin** [comment]
in quercus the only Tan I have listed is Luomeng Tan. Are you the same person?

**Comment by risserlin** [comment]
nevermind, mouse over and I get the full name.

**Comment by risserlin** [comment]
created repo - Luomeng Tan in the bcb420-2022 organizations and added you to the Students team. You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
If you have any issues please let me know.
