### ISSUE TITLE
RicoZong

### ISSUE THREAD

**Issue by RicoZong** [bcb420-2022/Student_Wiki#41]
Add repo for Ruicong Zong 
GitHub: RicoZong

**Comment by risserlin** [comment]
created repo - Ruicong Zong in the bcb420-2022 organizations and added you to the Students team. You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
If you have any issues please let me know.

**Comment by RicoZong** [comment]
Hi Professor Risserlin,

I did not relieve the inventation to the team so that I can not edit the student wiki to post my repo and my wiki link.
