### ISSUE TITLE
Xinyi Zhang

### ISSUE THREAD

**Issue by Xinyi371** [bcb420-2022/Student_Wiki#44]
Hi Dr.Isserlin, could you please add my username Xinyi371 to the organization? Thank you very much.

**Comment by risserlin** [comment]
created repo - Xinyi Zhang in the bcb420-2022 organizations and added you to the Students team. You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
If you have any issues please let me know.
