### ISSUE TITLE
BCB420 GitHub Username: ElKju

### ISSUE THREAD

**Issue by ElKju** [bcb420-2022/Student_Wiki#46]

**Comment by risserlin** [comment]
student name?

**Comment by ElKju** [comment]
Soh, Li Quan 
uotird: sohli

**Comment by risserlin** [comment]
created repo - Li Soh in the bcb420-2022 organizations and added you to the Students team. You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
If you have any issues please let me know.
